version: '3.9'

services:
  database:
    image: mysql
    container_name: database
    environment:
      - MYSQL_DATABASE=work_timer
      - MYSQL_ROOT_PASSWORD=4adf05ec
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - work_times_network
    
  
  api:
    build: ./server
    container_name: api
    ports:
      - 3333:3333
      - 9229:9229
    volumes: 
      - ./server:/usr/app
    depends_on:
      - database
    networks:
      - work_times_network
    environment:
      -  VIRTUAL_HOST=api.worktimes.localhost
 
  
  client:
    build: ./client
    container_name: client
    ports: 
      - 5173:5173
    volumes: 
      - ./client:/usr/app
    depends_on:
      - api
    networks:
      - work_times_network
    environment:
      -  VIRTUAL_HOST=worktimes.localhost

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    networks:
      - work_times_network
    depends_on:
      - client
      - api
   

volumes:
  db:
    driver: local

networks:
 work_times_network:
    driver:
      bridge